### ISSUE TITLE
Custom Component

### ISSUE THREAD

**Issue by Initsnow** [JL710/iced-guide#11]
Deprecated since 0.13.0: components introduce encapsulated state and hamper the use of a single source of truth. Instead, leverage the Elm Architecture directly, or implement a custom widget
https://docs.rs/iced/latest/iced/widget/fn.component.html

**Comment by Initsnow** [comment]
And the code of [Structuring Apps](https://jl710.github.io/iced-guide/app_structure/app_structure.html) seems like can't build successfully

**Comment by JL710** [comment]
> Deprecated since 0.13.0: components introduce encapsulated state and hamper the use of a single source of truth. Instead, leverage the Elm Architecture directly, or implement a custom widget https://docs.rs/iced/latest/iced/widget/fn.component.html

Yup. I think the section can stay. But it might be a good idea to note that it is deprecated.
Do you might want to add the note?

**Comment by JL710** [comment]
> And the code of [Structuring Apps](https://jl710.github.io/iced-guide/app_structure/app_structure.html) seems like can't build successfully

Fixed it. It compiles again and uses version 0.13

**Comment by Initsnow** [comment]
None, and this is a great tutorial for beginners
